server {
  listen 80;
  server_name _;
  absolute_redirect off;
  port_in_redirect off;

  root /usr/share/nginx/html;
  index index.html;

  location /assets/ {
    try_files $uri =404;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location /factory/ {
    try_files $uri =404;
    expires 30d;
    add_header Cache-Control "public";
  }

  location /products/ {
    try_files $uri $uri/ /index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

  location = /50x.html {
    root /usr/share/nginx/html;
  }
}
