export const PRODUCT_IMAGES = {
  disc: '/products/disc-spring.jpg',
  hot: '/products/hot-coil-spring.jpg',
  compression: '/products/compression-spring.jpg',
  extension: '/products/extension-spring.jpg',
  torsion: '/products/torsion-spring.jpg',
  die: '/products/die-spring.jpg',
  custom: '/products/custom-wire-form.jpg',
  wave: '/products/wave-spring.jpg',
  retaining: '/products/retaining-ring.jpg',
  discStack: '/products/disc-stack.jpg',
  contact: '/products/contact-spring.jpg',
  constantForce: '/products/constant-force-spring.jpg',
  garter: '/products/garter-spring.jpg',
  flat: '/products/flat-spring.jpg',
  power: '/products/power-spring.jpg',
  variableForce: '/products/variable-force-spring.png',
  spiral: '/products/spiral-spring.jpg',
  contactClips: '/products/contact-clips.jpg',
  multiTurnWave: '/products/multi-turn-wave-spring.jpg',
} as const;
